#!/usr/bin/env python
"""
JTrack personal planner

Usage:
  jt <db> li [<id>]

"""
from lib.docopt import docopt
from lib import model, view
from sqlite3 import connect

if __name__ == '__main__':
    arguments = docopt(__doc__)
    conn = connect(arguments['<db>'])
    if arguments['li']:
        view.print_tree(conn, arguments)
